# Generated by Django 5.0.1 on 2024-01-23 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='PlaceFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Откуда',
                'verbose_name_plural': 'Откуда',
            },
        ),
        migrations.CreateModel(
            name='PlaceImpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Место прибытия',
                'verbose_name_plural': 'Места прибытия',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название')),
                ('date_of_create', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата создания заказа')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.car', verbose_name='Машина')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product', verbose_name='Продукция')),
                ('placeFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.placefrom', verbose_name='Откуда')),
                ('placeImpl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.placeimpl', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Откуда',
                'verbose_name_plural': 'Откуда',
            },
        ),
    ]
