# Generated by Django 5.0.1 on 2024-01-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_client_placefrom_placeimpl_alter_car_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
    ]
